version: "3.7"
services:
  app1:
    build: .
    hostname: "foo.dev"
    environment:
      - RELEASE_NODE=app@foo.dev
      - RELEASE_DISTRIBUTION=name
      - COOKIE=foobar
    depends_on:
      - db
    ports:
      - "127.0.0.1:4001:4001"
  app2:
    build: .
    hostname: "bar.dev"
    environment:
      - RELEASE_NODE=app@bar.dev
      - RELEASE_DISTRIBUTION=name
      - COOKIE=foobar
    depends_on:
      - db
    ports:
      - "127.0.0.1:4002:4001"
  db:
    image: "postgres:11"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=10000 -c pg_stat_statements.track=all
    environment:
      POSTGRES_DB: "cluster_example_dev"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "foobar"
      POSTGRES_HOST_AUTH_METHOD: "md5"
    container_name: "cluster_example_dev_db"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local